accent = "#509475"
cursor = "#D7C995"
foreground = "#C1C497"
foreground-muted = "#53685B"
background = "#111c18"
surface = "#23372B"
surface0 = "#1a2c22"
surface1 = "#364538"
surface2 = "#4a5d50"
selection_foreground = "#111C18"
selection_background = "#C1C497"

color0 = "#23372B"
color1 = "#FF5345"
color2 = "#549e6a"
color3 = "#459451"
color4 = "#509475"
color5 = "#D2689C"
color6 = "#2DD5B7"
color7 = "#F6F5DD"
color8 = "#53685B"
color9 = "#db9f9c"
color10 = "#63b07a"
color11 = "#E5C736"
color12 = "#ACD4CF"
color13 = "#75bbb3"
color14 = "#8CD3CB"
color15 = "#9eebb3"

red = "#FF5345"
green = "#549e6a"
blue = "#509475"
peach = "#D7C995"
yellow = "#E5C736"

flamingo = "#D2689C"
mauve = "#509475"
maroon = "#FF5345"
pink = "#D2689C"
lavender = "#ACD4CF"
sky = "#75bbb3"
teal = "#2DD5B7"
sapphire = "#509475"
accent-dim = "#4a5d50"
rosewater = "#F6F5DD"