# Set programs
$terminal = kitty
$launcher = launch-walker


# Undind
unbind = SUPER, W
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, T

bindd = SUPER, Space, Launcher, exec, $launcher
bindd = SUPER, Escape, Power menu, exec, romarchy-power-menu
bindd = SUPER CTRL, L, Lock screen, exec, romarchy-lock-screen
bindd = SUPER, Q, Close current window, killactive
bindd = SUPER ALT, K, Show key bindings, exec, omarchy-menu-keybindings
bindd = SUPER ALT, P, Power profile, exec, omarchy-menu power

# Application bindings
bindd = SUPER, T, Terminal, exec, uwsm-app -- $terminal 
bindd = SUPER, E, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, omarchy-launch-browser
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER CTRL, C, VS Code, exec, uwsm app -- code
bindd = SUPER ALT, T, Activity monitor, exec, omarchy-launch-tui btop
bindd = SUPER, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
# bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER, slash, Passwords, exec, uwsm app -- bitwarden-desktop

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-webapp "https://discord.com/channels/@me"
bindd = SUPER SHIFT, C, Claude, exec, omarchy-launch-webapp "https://claude.ai"
bindd = SUPER CTRL, G, GitHub, exec, omarchy-launch-webapp "https://github.com"
bindd = SUPER SHIFT, G, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"

# Window Actions
bindd = SUPER SHIFT, J, Toggle split, togglesplit, # dwindle
bindd = SUPER SHIFT, T, Toggle floating, togglefloating,

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

# Swap active window with the one next to it with SUPER + SHIFT + arrow keys
bindd = SUPER SHIFT, h, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, l, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, k, Swap window up, swapwindow, u
bindd = SUPER SHIFT, j, Swap window down, swapwindow, d

bindd = SUPER, R, Activates window resizing mode, submap, resize
submap = resize
bindd = , L, Resize to the right (resizing mode), resizeactive, 15 0
bindd = , H, Resize to the left (resizing mode), resizeactive, -15 0
bindd = , K, Resize upwards (resizing mode), resizeactive, 0 -15
bindd = , J, Resize downwards (resizing mode), resizeactive, 0 15
bindd = , escape, Ends window resizing mode, submap, reset
submap = reset

bindd = SUPER CTRL SHIFT, L, Resize to the right, resizeactive, 15 0
bindd = SUPER CTRL SHIFT, H, Resize to the left, resizeactive, -15 0
bindd = SUPER CTRL SHIFT, K, Resize upwards, resizeactive, 0 -15
bindd = SUPER CTRL SHIFT, J, Resize downwards, resizeactive, 0 15

# bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, SPACE
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu
