background {
    monitor =
    path = ~/.config/hypr/wallpapers/default.png
    blur_passes = 3
}

label {
    monitor =
    text = cmd[mod]echo $TIME
    color = rgba(ffffffaa)
    font_family = CaskaydiaCove Nerd Font
    font_size = 64
    position = 0, -100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    placeholder_text = Type password...
    fail_text = Wrong password
    position = 0, 100
    halign = center
    valign = center
}
