# Romarchy Hyprland Configuration

# Source all config files
source = ~/.local/share/romarchy/config/hypr/envs.conf
source = ~/.local/share/romarchy/config/hypr/monitors.conf
source = ~/.local/share/romarchy/config/hypr/programs.conf
source = ~/.local/share/romarchy/config/hypr/input.conf
source = ~/.local/share/romarchy/config/hypr/looknfeel.conf
source = ~/.local/share/romarchy/config/hypr/autostart.conf
source = ~/.local/share/romarchy/config/hypr/bindings.conf
source = ~/.local/share/romarchy/config/hypr/windowrules.conf


