# Media keys
bindl = ,XF86AudioRaiseVolume, exec, volume-display +5%
bindl = ,XF86AudioLowerVolume, exec, volume-display -5%
bindl = ,XF86AudioMute, exec, volume-display toggle
bindl = ,XF86AudioPlay, exec, playerctl play-pause
bindl = ,XF86AudioNext, exec, playerctl next
bindl = ,XF86AudioPrev, exec, playerctl previous

# Brightness
bindl = ,XF86MonBrightnessUp, exec, brightness-display +5%
bindl = ,XF86MonBrightnessDown, exec, brightness-display -5%
