# Programs
$launcher = launch-walker

# Launcher
bindd = SUPER, Space, Launcher, exec, $launcher
bindd = SUPER ALT, Space, Menu, exec, launch-menu
bindd = SUPER CTRL, SPACE, Backgrounds, exec, launch-bg-picker
bindd = SUPER, Escape, Power menu, exec, launch-power-menu
bindd = SUPER CTRL, L, Lock screen, exec, lock-screen

# Apps
bindd = SUPER, Q, Close window, killactive
bindd = SUPER, T, Terminal, exec, launch-terminal
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER, Y, Yazi File manager, exec, launch-yazi
bindd = SUPER, E, File manager, exec, uwsm app -- nautilus
bindd = SUPER, B, Browser, exec, launch-browser
bindd = SUPER, N, Editor, exec, launch-editor
bindd = SUPER CTRL, C, VS Code, exec, uwsm app -- code

# Web Apps
bindd = SUPER SHIFT, Y, YouTube, exec, launch-webapp https://youtube.com
bindd = SUPER SHIFT, A, AI Picker, exec, ai-picker

# System monitors
bindd = CTRL ALT, Delete, Activity monitor, exec, launch-or-focus-tui btop

# System
bindd = SUPER CTRL, W, Restart waybar, exec, restart-waybar

# Screenshot
bindd = , PRINT, Screenshot, exec, screenshot
bindd = SHIFT, PRINT, Screenshot fullscreen, exec, screenshot fullscreen
bindd = SUPER ALT, comma, Edit last screenshot, exec, screenshot-edit

# Notifications
bindd = SUPER, comma, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, comma, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "$(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"
bindd = SUPER CTRL ALT, B, Show battery, exec, notify-send -u low "$(battery-status)"

# Mouse
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
